# generated by datamodel-codegen:
#   filename:  ai-service.openapi.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class PublishPlatform(StrEnum):
    douyin = "douyin"
    wechat = "wechat"
    x = "x"
    zhihu = "zhihu"


class DraftFormat(StrEnum):
    html = "html"
    markdown = "markdown"
    text = "text"


class GeneratedByType(StrEnum):
    agent = "agent"
    system = "system"
    user = "user"


class AdaptedAssetType(StrEnum):
    image = "image"


class GeneratedBy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: GeneratedByType
    id: constr(min_length=1)
    version: str | None = None
    agent_run_id: str | None = None
    instructions: str | None = None


class AdaptedAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: AdaptedAssetType
    source_url: constr(min_length=1)
    alt: str | None = None


class AdaptedContent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1) | None = None
    format: DraftFormat
    summary: str | None = None
    source_revision: str | None = Field(
        None, description="RFC3339 timestamp or a future revision identifier."
    )
    generated_by: GeneratedBy | None = None
    html: str | None = None
    markdown: str | None = None
    text: str | None = None
    assets: list[AdaptedAsset] | None = None
