// Code generated by contracts/generate-platform-capabilities.ts; DO NOT EDIT.

package platformcapabilities

type DraftCapability struct {
	Profile       string
	SchemaVersion int
	Format        string
}

type PublishingCapability struct {
	Modes                    []string
	PreferredMode            string
	AutoPublishAllowed       bool
	UsesStoredBrowserCookies bool
}

type FrontendCapability struct {
	Tab          bool
	LabelKey     string
	DefaultLabel string
	Icon         string
}

type ExtensionCapability struct {
	BackendHandoff     bool
	SupportedModes     []string
	PreferredMode      string
	AdapterKey         string
	InjectURL          string
	InjectURLs         []string
	ContentKinds       []string
	HandoffContentKind string
	TargetFormats      []string
	RequiresReview     bool
	AutoPublishAllowed bool
	ScriptFile         string
}

type AccountCapability struct {
	Mode string
}

type PlatformCapability struct {
	Key         string
	DisplayName string
	Project     bool
	Draft       *DraftCapability
	Publishing  PublishingCapability
	Account     AccountCapability
	Frontend    FrontendCapability
	Extension   *ExtensionCapability
}

type ExtensionHandoffConfig struct {
	AdapterKey     string
	InjectURL      string
	ContentKind    string
	RequiresReview bool
	AutoPublish    bool
}

const SchemaVersion = 1

var Capabilities = []PlatformCapability{
	{
		Key:         "wechat",
		DisplayName: "WeChat",
		Project:     true,
		Draft:       &DraftCapability{Profile: "wechat@v1", SchemaVersion: 1, Format: "html"},
		Publishing: PublishingCapability{
			Modes:                    []string{"api"},
			PreferredMode:            "api",
			AutoPublishAllowed:       true,
			UsesStoredBrowserCookies: false,
		},
		Account: AccountCapability{Mode: "api_credentials"},
		Frontend: FrontendCapability{
			Tab:          true,
			LabelKey:     "platforms.wechat",
			DefaultLabel: "WeChat",
			Icon:         "/icons/platforms/wechat.svg",
		},
		Extension: nil,
	},
	{
		Key:         "zhihu",
		DisplayName: "Zhihu",
		Project:     true,
		Draft:       &DraftCapability{Profile: "zhihu@v1", SchemaVersion: 1, Format: "markdown"},
		Publishing: PublishingCapability{
			Modes:                    []string{"headless_browser", "extension"},
			PreferredMode:            "headless_browser",
			AutoPublishAllowed:       true,
			UsesStoredBrowserCookies: true,
		},
		Account: AccountCapability{Mode: "browser_cookies"},
		Frontend: FrontendCapability{
			Tab:          true,
			LabelKey:     "platforms.zhihu",
			DefaultLabel: "Zhihu",
			Icon:         "/icons/platforms/zhihu.svg",
		},
		Extension: &ExtensionCapability{
			BackendHandoff:     false,
			SupportedModes:     []string{"extension", "remote"},
			PreferredMode:      "extension",
			AdapterKey:         "ARTICLE_ZHIHU",
			InjectURL:          "https://zhuanlan.zhihu.com/write",
			InjectURLs:         nil,
			ContentKinds:       []string{"article"},
			HandoffContentKind: "article",
			TargetFormats:      []string{"markdown", "html"},
			RequiresReview:     true,
			AutoPublishAllowed: false,
			ScriptFile:         "/content-scripts/zhihu-article.js",
		},
	},
	{
		Key:         "x",
		DisplayName: "X",
		Project:     true,
		Draft:       &DraftCapability{Profile: "x@v1", SchemaVersion: 1, Format: "text"},
		Publishing: PublishingCapability{
			Modes:                    []string{"api", "extension"},
			PreferredMode:            "api",
			AutoPublishAllowed:       true,
			UsesStoredBrowserCookies: false,
		},
		Account: AccountCapability{Mode: "oauth2"},
		Frontend: FrontendCapability{
			Tab:          true,
			LabelKey:     "platforms.x",
			DefaultLabel: "X",
			Icon:         "/icons/platforms/x.svg",
		},
		Extension: &ExtensionCapability{
			BackendHandoff:     true,
			SupportedModes:     []string{"extension"},
			PreferredMode:      "extension",
			AdapterKey:         "POST_X",
			InjectURL:          "https://x.com/compose/post",
			InjectURLs:         nil,
			ContentKinds:       []string{"dynamic_post"},
			HandoffContentKind: "dynamic_post",
			TargetFormats:      []string{"text"},
			RequiresReview:     true,
			AutoPublishAllowed: false,
			ScriptFile:         "/content-scripts/x-post.js",
		},
	},
	{
		Key:         "douyin",
		DisplayName: "Douyin",
		Project:     true,
		Draft:       &DraftCapability{Profile: "douyin@v1", SchemaVersion: 1, Format: "text"},
		Publishing: PublishingCapability{
			Modes:                    []string{"extension"},
			PreferredMode:            "extension",
			AutoPublishAllowed:       false,
			UsesStoredBrowserCookies: true,
		},
		Account: AccountCapability{Mode: "browser_cookies"},
		Frontend: FrontendCapability{
			Tab:          true,
			LabelKey:     "platforms.douyin",
			DefaultLabel: "Douyin",
			Icon:         "/icons/platforms/douyin.svg",
		},
		Extension: &ExtensionCapability{
			BackendHandoff:     true,
			SupportedModes:     []string{"extension"},
			PreferredMode:      "extension",
			AdapterKey:         "DYNAMIC_DOUYIN",
			InjectURL:          "https://creator.douyin.com/creator-micro/content/upload?default-tab=5",
			InjectURLs:         []string{"https://creator.douyin.com/creator-micro/content/upload", "https://creator.douyin.com/creator-micro/content/post/article"},
			ContentKinds:       []string{"article", "image_video"},
			HandoffContentKind: "article",
			TargetFormats:      []string{"text"},
			RequiresReview:     true,
			AutoPublishAllowed: false,
			ScriptFile:         "/content-scripts/douyin-dynamic.js",
		},
	},
	{
		Key:         "xiaohongshu",
		DisplayName: "Xiaohongshu",
		Project:     false,
		Draft:       nil,
		Publishing: PublishingCapability{
			Modes:                    []string{"extension"},
			PreferredMode:            "extension",
			AutoPublishAllowed:       false,
			UsesStoredBrowserCookies: false,
		},
		Account: AccountCapability{Mode: "local_browser"},
		Frontend: FrontendCapability{
			Tab:          false,
			LabelKey:     "platforms.xiaohongshu",
			DefaultLabel: "Xiaohongshu",
			Icon:         "/icons/platforms/xiaohongshu.svg",
		},
		Extension: &ExtensionCapability{
			BackendHandoff:     false,
			SupportedModes:     []string{"extension"},
			PreferredMode:      "extension",
			AdapterKey:         "NOTE_XIAOHONGSHU",
			InjectURL:          "https://creator.xiaohongshu.com/publish/publish",
			InjectURLs:         nil,
			ContentKinds:       []string{"image_note"},
			HandoffContentKind: "image_note",
			TargetFormats:      []string{"text"},
			RequiresReview:     true,
			AutoPublishAllowed: false,
			ScriptFile:         "/content-scripts/xiaohongshu-note.js",
		},
	},
	{
		Key:         "bilibili",
		DisplayName: "Bilibili",
		Project:     false,
		Draft:       nil,
		Publishing: PublishingCapability{
			Modes:                    []string{"extension"},
			PreferredMode:            "extension",
			AutoPublishAllowed:       false,
			UsesStoredBrowserCookies: false,
		},
		Account: AccountCapability{Mode: "local_browser"},
		Frontend: FrontendCapability{
			Tab:          false,
			LabelKey:     "platforms.bilibili",
			DefaultLabel: "Bilibili",
			Icon:         "/icons/platforms/bilibili.svg",
		},
		Extension: &ExtensionCapability{
			BackendHandoff:     false,
			SupportedModes:     []string{"extension"},
			PreferredMode:      "extension",
			AdapterKey:         "DYNAMIC_BILIBILI",
			InjectURL:          "https://t.bilibili.com",
			InjectURLs:         nil,
			ContentKinds:       []string{"dynamic_post"},
			HandoffContentKind: "dynamic_post",
			TargetFormats:      []string{"text"},
			RequiresReview:     true,
			AutoPublishAllowed: false,
			ScriptFile:         "/content-scripts/bilibili-dynamic.js",
		},
	},
}

var ProjectPlatformKeys = []string{"wechat", "zhihu", "x", "douyin"}

var ExtensionHandoffPlatformKeys = []string{"x", "douyin"}

var storedBrowserCookiePlatformSet = map[string]struct{}{
	"zhihu":  {},
	"douyin": {},
}

var extensionHandoffConfigs = map[string]ExtensionHandoffConfig{
	"x": {
		AdapterKey:     "POST_X",
		InjectURL:      "https://x.com/compose/post",
		ContentKind:    "dynamic_post",
		RequiresReview: true,
		AutoPublish:    false,
	},
	"douyin": {
		AdapterKey:     "DYNAMIC_DOUYIN",
		InjectURL:      "https://creator.douyin.com/creator-micro/content/upload?default-tab=5",
		ContentKind:    "article",
		RequiresReview: true,
		AutoPublish:    false,
	},
}

func ProjectPlatformSet() map[string]struct{} {
	return stringSet(ProjectPlatformKeys)
}

func ExtensionHandoffConfigFor(platform string) (ExtensionHandoffConfig, bool) {
	config, ok := extensionHandoffConfigs[platform]
	return config, ok
}

func UsesStoredBrowserCookies(platform string) bool {
	_, ok := storedBrowserCookiePlatformSet[platform]
	return ok
}

func stringSet(values []string) map[string]struct{} {
	set := make(map[string]struct{}, len(values))
	for _, value := range values {
		set[value] = struct{}{}
	}
	return set
}
