// Package contracts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package contracts

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AIChatMessageRole.
const (
	AIChatMessageRoleAssistant AIChatMessageRole = "assistant"
	AIChatMessageRoleUser      AIChatMessageRole = "user"
)

// Defines values for AIEditContentResponseChannel.
const (
	Content AIEditContentResponseChannel = "content"
)

// Defines values for AIEditPrepublishRequestPlatform.
const (
	AIEditPrepublishRequestPlatformDouyin AIEditPrepublishRequestPlatform = "douyin"
	AIEditPrepublishRequestPlatformWechat AIEditPrepublishRequestPlatform = "wechat"
	AIEditPrepublishRequestPlatformX      AIEditPrepublishRequestPlatform = "x"
	AIEditPrepublishRequestPlatformZhihu  AIEditPrepublishRequestPlatform = "zhihu"
)

// Defines values for AIEditPrepublishResponseChannel.
const (
	Prepublish AIEditPrepublishResponseChannel = "prepublish"
)

// Defines values for AIEditPrepublishResponsePlatform.
const (
	AIEditPrepublishResponsePlatformDouyin AIEditPrepublishResponsePlatform = "douyin"
	AIEditPrepublishResponsePlatformWechat AIEditPrepublishResponsePlatform = "wechat"
	AIEditPrepublishResponsePlatformX      AIEditPrepublishResponsePlatform = "x"
	AIEditPrepublishResponsePlatformZhihu  AIEditPrepublishResponsePlatform = "zhihu"
)

// Defines values for AdaptedAssetType.
const (
	Image AdaptedAssetType = "image"
)

// Defines values for BrowserSessionPlatform.
const (
	BrowserSessionPlatformDouyin BrowserSessionPlatform = "douyin"
	BrowserSessionPlatformWechat BrowserSessionPlatform = "wechat"
	BrowserSessionPlatformX      BrowserSessionPlatform = "x"
	BrowserSessionPlatformZhihu  BrowserSessionPlatform = "zhihu"
)

// Defines values for BrowserSessionStatus.
const (
	BrowserSessionStatusCapturing     BrowserSessionStatus = "capturing"
	BrowserSessionStatusConnected     BrowserSessionStatus = "connected"
	BrowserSessionStatusExpired       BrowserSessionStatus = "expired"
	BrowserSessionStatusFailed        BrowserSessionStatus = "failed"
	BrowserSessionStatusLoginDetected BrowserSessionStatus = "login_detected"
	BrowserSessionStatusPending       BrowserSessionStatus = "pending"
	BrowserSessionStatusReady         BrowserSessionStatus = "ready"
)

// Defines values for BrowserWorkerDomainRuleMatch.
const (
	Exact  BrowserWorkerDomainRuleMatch = "exact"
	Suffix BrowserWorkerDomainRuleMatch = "suffix"
)

// Defines values for BrowserWorkerSessionStatus.
const (
	BrowserWorkerSessionStatusLoginDetected BrowserWorkerSessionStatus = "login_detected"
	BrowserWorkerSessionStatusReady         BrowserWorkerSessionStatus = "ready"
)

// Defines values for CollabDocumentRole.
const (
	Editor CollabDocumentRole = "editor"
	Viewer CollabDocumentRole = "viewer"
)

// Defines values for CollabDocumentStatus.
const (
	Active CollabDocumentStatus = "active"
)

// Defines values for CompleteBrowserSessionResultPlatform.
const (
	CompleteBrowserSessionResultPlatformDouyin CompleteBrowserSessionResultPlatform = "douyin"
	CompleteBrowserSessionResultPlatformWechat CompleteBrowserSessionResultPlatform = "wechat"
	CompleteBrowserSessionResultPlatformX      CompleteBrowserSessionResultPlatform = "x"
	CompleteBrowserSessionResultPlatformZhihu  CompleteBrowserSessionResultPlatform = "zhihu"
)

// Defines values for ConnectionTestStatus.
const (
	ConnectionTestStatusConnected ConnectionTestStatus = "connected"
	ConnectionTestStatusFailed    ConnectionTestStatus = "failed"
)

// Defines values for ContentTemplateDefaultPlatforms.
const (
	ContentTemplateDefaultPlatformsDouyin ContentTemplateDefaultPlatforms = "douyin"
	ContentTemplateDefaultPlatformsWechat ContentTemplateDefaultPlatforms = "wechat"
	ContentTemplateDefaultPlatformsX      ContentTemplateDefaultPlatforms = "x"
	ContentTemplateDefaultPlatformsZhihu  ContentTemplateDefaultPlatforms = "zhihu"
)

// Defines values for ContentTemplateScope.
const (
	ContentTemplateScopePersonal  ContentTemplateScope = "personal"
	ContentTemplateScopeSystem    ContentTemplateScope = "system"
	ContentTemplateScopeWorkspace ContentTemplateScope = "workspace"
)

// Defines values for CreateContentTemplateRequestDefaultPlatforms.
const (
	CreateContentTemplateRequestDefaultPlatformsDouyin CreateContentTemplateRequestDefaultPlatforms = "douyin"
	CreateContentTemplateRequestDefaultPlatformsWechat CreateContentTemplateRequestDefaultPlatforms = "wechat"
	CreateContentTemplateRequestDefaultPlatformsX      CreateContentTemplateRequestDefaultPlatforms = "x"
	CreateContentTemplateRequestDefaultPlatformsZhihu  CreateContentTemplateRequestDefaultPlatforms = "zhihu"
)

// Defines values for DouyinAccountPlatform.
const (
	DouyinAccountPlatformDouyin DouyinAccountPlatform = "douyin"
)

// Defines values for DraftFormat.
const (
	Html     DraftFormat = "html"
	Markdown DraftFormat = "markdown"
	Text     DraftFormat = "text"
)

// Defines values for GeneratedByType.
const (
	GeneratedByTypeAgent  GeneratedByType = "agent"
	GeneratedByTypeSystem GeneratedByType = "system"
	GeneratedByTypeUser   GeneratedByType = "user"
)

// Defines values for MediaAssetLibraryScope.
const (
	MediaAssetLibraryScopePersonal  MediaAssetLibraryScope = "personal"
	MediaAssetLibraryScopeProject   MediaAssetLibraryScope = "project"
	MediaAssetLibraryScopeWorkspace MediaAssetLibraryScope = "workspace"
)

// Defines values for PlatformAccountStatus.
const (
	PlatformAccountStatusConnected    PlatformAccountStatus = "connected"
	PlatformAccountStatusFailed       PlatformAccountStatus = "failed"
	PlatformAccountStatusUnconfigured PlatformAccountStatus = "unconfigured"
	PlatformAccountStatusUntested     PlatformAccountStatus = "untested"
)

// Defines values for ProjectAccessSource.
const (
	ProjectAccessSourceDirectShare ProjectAccessSource = "direct_share"
	ProjectAccessSourceOwner       ProjectAccessSource = "owner"
	ProjectAccessSourceWorkspace   ProjectAccessSource = "workspace"
)

// Defines values for ProjectActivityType.
const (
	ProjectActivityTypeCollaboratorAdded       ProjectActivityType = "collaborator_added"
	ProjectActivityTypeCollaboratorRemoved     ProjectActivityType = "collaborator_removed"
	ProjectActivityTypeCollaboratorRoleChanged ProjectActivityType = "collaborator_role_changed"
	ProjectActivityTypeCommentCreated          ProjectActivityType = "comment_created"
	ProjectActivityTypeCommentResolved         ProjectActivityType = "comment_resolved"
	ProjectActivityTypeContentSaved            ProjectActivityType = "content_saved"
	ProjectActivityTypePublishCompleted        ProjectActivityType = "publish_completed"
	ProjectActivityTypePublishQueued           ProjectActivityType = "publish_queued"
	ProjectActivityTypePublishRequested        ProjectActivityType = "publish_requested"
	ProjectActivityTypeShareLinkAccepted       ProjectActivityType = "share_link_accepted"
	ProjectActivityTypeShareLinkCreated        ProjectActivityType = "share_link_created"
	ProjectActivityTypeShareLinkRevoked        ProjectActivityType = "share_link_revoked"
	ProjectActivityTypeVersionRestored         ProjectActivityType = "version_restored"
)

// Defines values for ProjectCollaboratorRole.
const (
	ProjectCollaboratorRoleEditor ProjectCollaboratorRole = "editor"
	ProjectCollaboratorRoleViewer ProjectCollaboratorRole = "viewer"
)

// Defines values for ProjectCommentStatus.
const (
	ProjectCommentStatusOpen     ProjectCommentStatus = "open"
	ProjectCommentStatusResolved ProjectCommentStatus = "resolved"
)

// Defines values for ProjectRole.
const (
	ProjectRoleEditor ProjectRole = "editor"
	ProjectRoleOwner  ProjectRole = "owner"
	ProjectRoleViewer ProjectRole = "viewer"
)

// Defines values for ProjectShareLinkStatus.
const (
	ProjectShareLinkStatusActive  ProjectShareLinkStatus = "active"
	ProjectShareLinkStatusRevoked ProjectShareLinkStatus = "revoked"
)

// Defines values for ProjectStatus.
const (
	ProjectStatusDraft      ProjectStatus = "draft"
	ProjectStatusFailed     ProjectStatus = "failed"
	ProjectStatusPublished  ProjectStatus = "published"
	ProjectStatusPublishing ProjectStatus = "publishing"
	ProjectStatusReady      ProjectStatus = "ready"
)

// Defines values for PublicationDetailPlatform.
const (
	PublicationDetailPlatformDouyin PublicationDetailPlatform = "douyin"
	PublicationDetailPlatformWechat PublicationDetailPlatform = "wechat"
	PublicationDetailPlatformX      PublicationDetailPlatform = "x"
	PublicationDetailPlatformZhihu  PublicationDetailPlatform = "zhihu"
)

// Defines values for PublicationDraftStatus.
const (
	PublicationDraftStatusReady    PublicationDraftStatus = "ready"
	PublicationDraftStatusStale    PublicationDraftStatus = "stale"
	PublicationDraftStatusSyncing  PublicationDraftStatus = "syncing"
	PublicationDraftStatusUnsynced PublicationDraftStatus = "unsynced"
)

// Defines values for PublicationReviewStatus.
const (
	PublicationReviewStatusApproved         PublicationReviewStatus = "approved"
	PublicationReviewStatusChangesRequested PublicationReviewStatus = "changes_requested"
	PublicationReviewStatusDraft            PublicationReviewStatus = "draft"
	PublicationReviewStatusReviewing        PublicationReviewStatus = "reviewing"
)

// Defines values for PublicationStatus.
const (
	PublicationStatusCancelled  PublicationStatus = "cancelled"
	PublicationStatusDraft      PublicationStatus = "draft"
	PublicationStatusFailed     PublicationStatus = "failed"
	PublicationStatusPublishing PublicationStatus = "publishing"
	PublicationStatusQueued     PublicationStatus = "queued"
	PublicationStatusSucceeded  PublicationStatus = "succeeded"
	PublicationStatusSyncing    PublicationStatus = "syncing"
)

// Defines values for PublicationSummaryPlatform.
const (
	PublicationSummaryPlatformDouyin PublicationSummaryPlatform = "douyin"
	PublicationSummaryPlatformWechat PublicationSummaryPlatform = "wechat"
	PublicationSummaryPlatformX      PublicationSummaryPlatform = "x"
	PublicationSummaryPlatformZhihu  PublicationSummaryPlatform = "zhihu"
)

// Defines values for PublishPlatform.
const (
	PublishPlatformDouyin PublishPlatform = "douyin"
	PublishPlatformWechat PublishPlatform = "wechat"
	PublishPlatformX      PublishPlatform = "x"
	PublishPlatformZhihu  PublishPlatform = "zhihu"
)

// Defines values for PublishResultPlatform.
const (
	PublishResultPlatformDouyin PublishResultPlatform = "douyin"
	PublishResultPlatformWechat PublishResultPlatform = "wechat"
	PublishResultPlatformX      PublishResultPlatform = "x"
	PublishResultPlatformZhihu  PublishResultPlatform = "zhihu"
)

// Defines values for PublishResultStatus.
const (
	PublishResultStatusError          PublishResultStatus = "error"
	PublishResultStatusFailed         PublishResultStatus = "failed"
	PublishResultStatusManualRequired PublishResultStatus = "manual_required"
	PublishResultStatusPublishing     PublishResultStatus = "publishing"
	PublishResultStatusQueued         PublishResultStatus = "queued"
	PublishResultStatusSucceeded      PublishResultStatus = "succeeded"
)

// Defines values for RequirementStatusValue.
const (
	RequirementStatusValueFailed  RequirementStatusValue = "failed"
	RequirementStatusValuePassed  RequirementStatusValue = "passed"
	RequirementStatusValueUnknown RequirementStatusValue = "unknown"
	RequirementStatusValueWarning RequirementStatusValue = "warning"
)

// Defines values for StartPublishBrowserSessionResultPlatform.
const (
	StartPublishBrowserSessionResultPlatformDouyin StartPublishBrowserSessionResultPlatform = "douyin"
	StartPublishBrowserSessionResultPlatformWechat StartPublishBrowserSessionResultPlatform = "wechat"
	StartPublishBrowserSessionResultPlatformX      StartPublishBrowserSessionResultPlatform = "x"
	StartPublishBrowserSessionResultPlatformZhihu  StartPublishBrowserSessionResultPlatform = "zhihu"
)

// Defines values for UpdateProjectCommentRequestStatus.
const (
	Resolved UpdateProjectCommentRequestStatus = "resolved"
)

// Defines values for WechatAccountPlatform.
const (
	Wechat WechatAccountPlatform = "wechat"
)

// Defines values for WorkspaceActivityType.
const (
	WorkspaceActivityTypeInviteAccepted    WorkspaceActivityType = "invite_accepted"
	WorkspaceActivityTypeInviteCreated     WorkspaceActivityType = "invite_created"
	WorkspaceActivityTypeInviteRevoked     WorkspaceActivityType = "invite_revoked"
	WorkspaceActivityTypeMemberAdded       WorkspaceActivityType = "member_added"
	WorkspaceActivityTypeMemberRemoved     WorkspaceActivityType = "member_removed"
	WorkspaceActivityTypeMemberRoleChanged WorkspaceActivityType = "member_role_changed"
	WorkspaceActivityTypeWorkspaceCreated  WorkspaceActivityType = "workspace_created"
	WorkspaceActivityTypeWorkspaceUpdated  WorkspaceActivityType = "workspace_updated"
)

// Defines values for WorkspaceInviteStatus.
const (
	WorkspaceInviteStatusAccepted WorkspaceInviteStatus = "accepted"
	WorkspaceInviteStatusExpired  WorkspaceInviteStatus = "expired"
	WorkspaceInviteStatusPending  WorkspaceInviteStatus = "pending"
	WorkspaceInviteStatusRevoked  WorkspaceInviteStatus = "revoked"
)

// Defines values for WorkspaceInviteWithTokenStatus.
const (
	WorkspaceInviteWithTokenStatusAccepted WorkspaceInviteWithTokenStatus = "accepted"
	WorkspaceInviteWithTokenStatusExpired  WorkspaceInviteWithTokenStatus = "expired"
	WorkspaceInviteWithTokenStatusPending  WorkspaceInviteWithTokenStatus = "pending"
	WorkspaceInviteWithTokenStatusRevoked  WorkspaceInviteWithTokenStatus = "revoked"
)

// Defines values for WorkspaceMemberRequestRole.
const (
	WorkspaceMemberRequestRoleAdmin  WorkspaceMemberRequestRole = "admin"
	WorkspaceMemberRequestRoleMember WorkspaceMemberRequestRole = "member"
	WorkspaceMemberRequestRoleViewer WorkspaceMemberRequestRole = "viewer"
)

// Defines values for WorkspaceRole.
const (
	WorkspaceRoleAdmin  WorkspaceRole = "admin"
	WorkspaceRoleMember WorkspaceRole = "member"
	WorkspaceRoleOwner  WorkspaceRole = "owner"
	WorkspaceRoleViewer WorkspaceRole = "viewer"
)

// Defines values for WorkspaceStatus.
const (
	WorkspaceStatusActive   WorkspaceStatus = "active"
	WorkspaceStatusArchived WorkspaceStatus = "archived"
)

// Defines values for XAccountAuthType.
const (
	Oauth1 XAccountAuthType = "oauth1"
	Oauth2 XAccountAuthType = "oauth2"
)

// Defines values for XAccountPlatform.
const (
	X XAccountPlatform = "x"
)

// Defines values for ZhihuAccountPlatform.
const (
	Zhihu ZhihuAccountPlatform = "zhihu"
)

// AIChatMessage defines model for AIChatMessage.
type AIChatMessage struct {
	Content string            `json:"content"`
	Role    AIChatMessageRole `json:"role"`
}

// AIChatMessageRole defines model for AIChatMessage.Role.
type AIChatMessageRole string

// AIEditContentRequest defines model for AIEditContentRequest.
type AIEditContentRequest struct {
	Content      string           `json:"content"`
	Conversation *[]AIChatMessage `json:"conversation,omitempty"`
	Message      string           `json:"message"`
	Title        *string          `json:"title,omitempty"`
}

// AIEditContentResponse defines model for AIEditContentResponse.
type AIEditContentResponse struct {
	Channel AIEditContentResponseChannel `json:"channel"`
	Content string                       `json:"content"`
}

// AIEditContentResponseChannel defines model for AIEditContentResponse.Channel.
type AIEditContentResponseChannel string

// AIEditPrepublishRequest defines model for AIEditPrepublishRequest.
type AIEditPrepublishRequest struct {
	AdaptedContent struct {
		Assets        *[]AdaptedAsset `json:"assets,omitempty"`
		Format        DraftFormat     `json:"format"`
		GeneratedBy   *GeneratedBy    `json:"generated_by,omitempty"`
		Html          *string         `json:"html,omitempty"`
		Markdown      *string         `json:"markdown,omitempty"`
		SchemaVersion *int            `json:"schema_version,omitempty"`

		// SourceRevision RFC3339 timestamp or a future revision identifier.
		SourceRevision *string `json:"source_revision,omitempty"`
		Summary        *string `json:"summary,omitempty"`
		Text           *string `json:"text,omitempty"`
	} `json:"adapted_content"`
	Conversation *[]AIChatMessage                `json:"conversation,omitempty"`
	Message      string                          `json:"message"`
	Platform     AIEditPrepublishRequestPlatform `json:"platform"`
	Title        *string                         `json:"title,omitempty"`
}

// AIEditPrepublishRequestPlatform defines model for AIEditPrepublishRequest.Platform.
type AIEditPrepublishRequestPlatform string

// AIEditPrepublishResponse defines model for AIEditPrepublishResponse.
type AIEditPrepublishResponse struct {
	AdaptedContent struct {
		Assets        *[]AdaptedAsset `json:"assets,omitempty"`
		Format        DraftFormat     `json:"format"`
		GeneratedBy   *GeneratedBy    `json:"generated_by,omitempty"`
		Html          *string         `json:"html,omitempty"`
		Markdown      *string         `json:"markdown,omitempty"`
		SchemaVersion *int            `json:"schema_version,omitempty"`

		// SourceRevision RFC3339 timestamp or a future revision identifier.
		SourceRevision *string `json:"source_revision,omitempty"`
		Summary        *string `json:"summary,omitempty"`
		Text           *string `json:"text,omitempty"`
	} `json:"adapted_content"`
	Channel  AIEditPrepublishResponseChannel  `json:"channel"`
	Content  string                           `json:"content"`
	Platform AIEditPrepublishResponsePlatform `json:"platform"`
}

// AIEditPrepublishResponseChannel defines model for AIEditPrepublishResponse.Channel.
type AIEditPrepublishResponseChannel string

// AIEditPrepublishResponsePlatform defines model for AIEditPrepublishResponse.Platform.
type AIEditPrepublishResponsePlatform string

// AcceptProjectShareLinkResponse defines model for AcceptProjectShareLinkResponse.
type AcceptProjectShareLinkResponse struct {
	Project ProjectDetail `json:"project"`
	Role    ProjectRole   `json:"role"`
}

// AcceptWorkspaceInviteRequest defines model for AcceptWorkspaceInviteRequest.
type AcceptWorkspaceInviteRequest struct {
	Token string `json:"token"`
}

// AdaptedAsset defines model for AdaptedAsset.
type AdaptedAsset struct {
	Alt       *string          `json:"alt,omitempty"`
	SourceUrl string           `json:"source_url"`
	Type      AdaptedAssetType `json:"type"`
}

// AdaptedAssetType defines model for AdaptedAssetType.
type AdaptedAssetType string

// AdaptedContent defines model for AdaptedContent.
type AdaptedContent struct {
	Assets        *[]AdaptedAsset `json:"assets,omitempty"`
	Format        DraftFormat     `json:"format"`
	GeneratedBy   *GeneratedBy    `json:"generated_by,omitempty"`
	Html          *string         `json:"html,omitempty"`
	Markdown      *string         `json:"markdown,omitempty"`
	SchemaVersion *int            `json:"schema_version,omitempty"`

	// SourceRevision RFC3339 timestamp or a future revision identifier.
	SourceRevision *string `json:"source_revision,omitempty"`
	Summary        *string `json:"summary,omitempty"`
	Text           *string `json:"text,omitempty"`
}

// AddProjectCollaboratorRequest defines model for AddProjectCollaboratorRequest.
type AddProjectCollaboratorRequest struct {
	Email  *openapi_types.Email    `json:"email,omitempty"`
	Role   ProjectCollaboratorRole `json:"role"`
	UserId *openapi_types.UUID     `json:"user_id,omitempty"`
}

// AddWorkspaceMemberRequest defines model for AddWorkspaceMemberRequest.
type AddWorkspaceMemberRequest struct {
	Email  *openapi_types.Email       `json:"email,omitempty"`
	Role   WorkspaceMemberRequestRole `json:"role"`
	UserId *openapi_types.UUID        `json:"user_id,omitempty"`
}

// BrandProfile defines model for BrandProfile.
type BrandProfile struct {
	Audience     string             `json:"audience"`
	BannedWords  []string           `json:"banned_words"`
	CreatedAt    time.Time          `json:"created_at"`
	CreatedBy    openapi_types.UUID `json:"created_by"`
	Cta          string             `json:"cta"`
	DefaultTags  []string           `json:"default_tags"`
	Id           openapi_types.UUID `json:"id"`
	LinkStrategy string             `json:"link_strategy"`
	Name         string             `json:"name"`
	UpdatedAt    time.Time          `json:"updated_at"`
	Voice        string             `json:"voice"`
	WorkspaceId  openapi_types.UUID `json:"workspace_id"`
}

// BrandProfilesResponse defines model for BrandProfilesResponse.
type BrandProfilesResponse struct {
	Items []BrandProfile `json:"items"`
}

// BrowserSession defines model for BrowserSession.
type BrowserSession struct {
	ExpiresAt            time.Time              `json:"expires_at"`
	Message              *string                `json:"message,omitempty"`
	Platform             BrowserSessionPlatform `json:"platform"`
	SessionId            openapi_types.UUID     `json:"session_id"`
	Status               BrowserSessionStatus   `json:"status"`
	StreamTokenExpiresAt *time.Time             `json:"stream_token_expires_at,omitempty"`
	StreamUrl            *string                `json:"stream_url,omitempty"`
}

// BrowserSessionPlatform defines model for BrowserSession.Platform.
type BrowserSessionPlatform string

// BrowserSessionStatus defines model for BrowserSessionStatus.
type BrowserSessionStatus string

// BrowserWorkerCaptureSessionResponse defines model for BrowserWorkerCaptureSessionResponse.
type BrowserWorkerCaptureSessionResponse struct {
	Account        BrowserWorkerRemoteAccountProfile `json:"account"`
	Cookies        []BrowserWorkerCookie             `json:"cookies"`
	MissingCookies []string                          `json:"missing_cookies"`
	Status         BrowserWorkerSessionStatus        `json:"status"`
}

// BrowserWorkerCookie defines model for BrowserWorkerCookie.
type BrowserWorkerCookie struct {
	Domain   string  `json:"domain"`
	Expires  float64 `json:"expires"`
	HttpOnly bool    `json:"httpOnly"`
	Name     string  `json:"name"`
	Path     string  `json:"path"`
	SameSite string  `json:"sameSite"`
	Secure   bool    `json:"secure"`
	Value    string  `json:"value"`
}

// BrowserWorkerCookieRequirement defines model for BrowserWorkerCookieRequirement.
type BrowserWorkerCookieRequirement struct {
	DomainSuffixes []string `json:"domain_suffixes"`
	Name           string   `json:"name"`
	Preserve       bool     `json:"preserve"`
	Required       bool     `json:"required"`
}

// BrowserWorkerDomainRule defines model for BrowserWorkerDomainRule.
type BrowserWorkerDomainRule struct {
	Host    string                       `json:"host"`
	Match   BrowserWorkerDomainRuleMatch `json:"match"`
	Purpose string                       `json:"purpose"`
	Schemes []string                     `json:"schemes"`
}

// BrowserWorkerDomainRuleMatch defines model for BrowserWorkerDomainRule.Match.
type BrowserWorkerDomainRuleMatch string

// BrowserWorkerGetSessionResponse defines model for BrowserWorkerGetSessionResponse.
type BrowserWorkerGetSessionResponse struct {
	CurrentURL       string                     `json:"current_url"`
	LoginDetected    bool                       `json:"login_detected"`
	Message          string                     `json:"message"`
	MissingCookies   []string                   `json:"missing_cookies"`
	Status           BrowserWorkerSessionStatus `json:"status"`
	WorkerSessionRef string                     `json:"worker_session_ref"`
}

// BrowserWorkerRemoteAccountProfile defines model for BrowserWorkerRemoteAccountProfile.
type BrowserWorkerRemoteAccountProfile struct {
	AvatarURL      string `json:"avatar_url"`
	PlatformUserID string `json:"platform_user_id"`
	Username       string `json:"username"`
}

// BrowserWorkerSessionStatus defines model for BrowserWorkerSessionStatus.
type BrowserWorkerSessionStatus string

// BrowserWorkerStartDouyinPublishRequest defines model for BrowserWorkerStartDouyinPublishRequest.
type BrowserWorkerStartDouyinPublishRequest struct {
	Content          string `json:"content"`
	CoverImageBase64 string `json:"cover_image_base64"`
	CoverImageName   string `json:"cover_image_name"`
	Title            string `json:"title"`
}

// BrowserWorkerStartSessionRequest defines model for BrowserWorkerStartSessionRequest.
type BrowserWorkerStartSessionRequest struct {
	AllowedDomains  []BrowserWorkerDomainRule        `json:"allowed_domains"`
	InitialCookies  []BrowserWorkerCookie            `json:"initial_cookies"`
	LoginURL        string                           `json:"login_url"`
	Platform        string                           `json:"platform"`
	RequiredCookies []BrowserWorkerCookieRequirement `json:"required_cookies"`
	SessionID       openapi_types.UUID               `json:"session_id"`
	TTLSeconds      int                              `json:"ttl_seconds"`
	UserID          openapi_types.UUID               `json:"user_id"`
	Viewport        BrowserWorkerViewport            `json:"viewport"`
}

// BrowserWorkerStartSessionResponse defines model for BrowserWorkerStartSessionResponse.
type BrowserWorkerStartSessionResponse struct {
	CDPEndpointRef    string                     `json:"cdp_endpoint_ref"`
	ContainerID       string                     `json:"container_id"`
	ExpiresAt         time.Time                  `json:"expires_at"`
	StartedAt         time.Time                  `json:"started_at"`
	Status            BrowserWorkerSessionStatus `json:"status"`
	StreamEndpointRef string                     `json:"stream_endpoint_ref"`
	WorkerSessionRef  string                     `json:"worker_session_ref"`
}

// BrowserWorkerViewport defines model for BrowserWorkerViewport.
type BrowserWorkerViewport struct {
	Height int `json:"height"`
	Width  int `json:"width"`
}

// CancelBrowserSessionResult defines model for CancelBrowserSessionResult.
type CancelBrowserSessionResult struct {
	SessionId openapi_types.UUID   `json:"session_id"`
	Status    BrowserSessionStatus `json:"status"`
}

// CollabDocument defines model for CollabDocument.
type CollabDocument struct {
	CreatedAt     time.Time            `json:"created_at"`
	CurrentSeq    int64                `json:"current_seq"`
	Id            openapi_types.UUID   `json:"id"`
	LastEditedAt  *time.Time           `json:"last_edited_at"`
	LastEditedBy  *openapi_types.UUID  `json:"last_edited_by"`
	OwnerUserId   openapi_types.UUID   `json:"owner_user_id"`
	SchemaVersion int                  `json:"schema_version"`
	Status        CollabDocumentStatus `json:"status"`
	Title         string               `json:"title"`
	UpdatedAt     time.Time            `json:"updated_at"`
}

// CollabDocumentRole defines model for CollabDocumentRole.
type CollabDocumentRole string

// CollabDocumentSession defines model for CollabDocumentSession.
type CollabDocumentSession struct {
	DocumentId   openapi_types.UUID  `json:"document_id"`
	ExpiresAt    time.Time           `json:"expires_at"`
	Limits       CollabSessionLimits `json:"limits"`
	Role         CollabDocumentRole  `json:"role"`
	Token        string              `json:"token"`
	WebsocketUrl string              `json:"websocket_url"`
}

// CollabDocumentStatus defines model for CollabDocumentStatus.
type CollabDocumentStatus string

// CollabSessionLimits defines model for CollabSessionLimits.
type CollabSessionLimits struct {
	HeartbeatSeconds int `json:"heartbeat_seconds"`
	MaxMessageBytes  int `json:"max_message_bytes"`
}

// CompleteBrowserSessionResult defines model for CompleteBrowserSessionResult.
type CompleteBrowserSessionResult struct {
	Account struct {
		AvatarUrl string `json:"avatar_url"`
		Username  string `json:"username"`
	} `json:"account"`
	Message   string                               `json:"message"`
	Platform  CompleteBrowserSessionResultPlatform `json:"platform"`
	SessionId openapi_types.UUID                   `json:"session_id"`
	Status    BrowserSessionStatus                 `json:"status"`
}

// CompleteBrowserSessionResultPlatform defines model for CompleteBrowserSessionResult.Platform.
type CompleteBrowserSessionResultPlatform string

// ConnectionTestStatus defines model for ConnectionTestStatus.
type ConnectionTestStatus string

// ContentTemplate defines model for ContentTemplate.
type ContentTemplate struct {
	CreatedAt        time.Time                         `json:"created_at"`
	DefaultPlatforms []ContentTemplateDefaultPlatforms `json:"default_platforms"`
	Description      string                            `json:"description"`
	Id               openapi_types.UUID                `json:"id"`
	Name             string                            `json:"name"`
	OwnerUserId      *openapi_types.UUID               `json:"owner_user_id"`
	PlatformConfig   map[string]interface{}            `json:"platform_config"`
	Scope            ContentTemplateScope              `json:"scope"`
	SourceTemplate   string                            `json:"source_template"`
	Tags             []string                          `json:"tags"`
	TitleTemplate    string                            `json:"title_template"`
	UpdatedAt        time.Time                         `json:"updated_at"`
	WorkspaceId      *openapi_types.UUID               `json:"workspace_id"`
}

// ContentTemplateDefaultPlatforms defines model for ContentTemplate.DefaultPlatforms.
type ContentTemplateDefaultPlatforms string

// ContentTemplateScope defines model for ContentTemplateScope.
type ContentTemplateScope string

// ContentTemplatesResponse defines model for ContentTemplatesResponse.
type ContentTemplatesResponse struct {
	Items []ContentTemplate `json:"items"`
}

// CreateBrandProfileRequest defines model for CreateBrandProfileRequest.
type CreateBrandProfileRequest struct {
	Audience     *string   `json:"audience,omitempty"`
	BannedWords  *[]string `json:"banned_words,omitempty"`
	Cta          *string   `json:"cta,omitempty"`
	DefaultTags  *[]string `json:"default_tags,omitempty"`
	LinkStrategy *string   `json:"link_strategy,omitempty"`
	Name         string    `json:"name"`
	Voice        *string   `json:"voice,omitempty"`
}

// CreateCollabDocumentRequest defines model for CreateCollabDocumentRequest.
type CreateCollabDocumentRequest struct {
	Title string `json:"title"`
}

// CreateContentTemplateRequest defines model for CreateContentTemplateRequest.
type CreateContentTemplateRequest struct {
	DefaultPlatforms []CreateContentTemplateRequestDefaultPlatforms `json:"default_platforms"`
	Description      *string                                        `json:"description,omitempty"`
	Name             string                                         `json:"name"`
	PlatformConfig   *map[string]interface{}                        `json:"platform_config,omitempty"`
	Scope            *ContentTemplateScope                          `json:"scope,omitempty"`
	SourceTemplate   string                                         `json:"source_template"`
	Tags             *[]string                                      `json:"tags,omitempty"`
	TitleTemplate    string                                         `json:"title_template"`
}

// CreateContentTemplateRequestDefaultPlatforms defines model for CreateContentTemplateRequest.DefaultPlatforms.
type CreateContentTemplateRequestDefaultPlatforms string

// CreateProjectCommentRequest defines model for CreateProjectCommentRequest.
type CreateProjectCommentRequest struct {
	AnchorText *string                 `json:"anchor_text,omitempty"`
	Body       string                  `json:"body"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
}

// CreateProjectShareLinkRequest defines model for CreateProjectShareLinkRequest.
type CreateProjectShareLinkRequest struct {
	ExpiresAt *time.Time              `json:"expires_at,omitempty"`
	Role      ProjectCollaboratorRole `json:"role"`
}

// CreateWorkspaceInviteRequest defines model for CreateWorkspaceInviteRequest.
type CreateWorkspaceInviteRequest struct {
	Email     openapi_types.Email        `json:"email"`
	ExpiresAt *time.Time                 `json:"expires_at,omitempty"`
	Role      WorkspaceMemberRequestRole `json:"role"`
}

// CreateWorkspaceRequest defines model for CreateWorkspaceRequest.
type CreateWorkspaceRequest struct {
	Name string  `json:"name"`
	Slug *string `json:"slug,omitempty"`
}

// DashboardStats defines model for DashboardStats.
type DashboardStats struct {
	TotalFailedPublications    int `json:"total_failed_publications"`
	TotalProjects              int `json:"total_projects"`
	TotalPublishedPublications int `json:"total_published_publications"`
	TotalUsers                 int `json:"total_users"`
}

// DouyinAccount defines model for DouyinAccount.
type DouyinAccount struct {
	AvatarUrl     *string               `json:"avatar_url,omitempty"`
	LastTestError *string               `json:"last_test_error,omitempty"`
	LastTestedAt  *time.Time            `json:"last_tested_at,omitempty"`
	Platform      DouyinAccountPlatform `json:"platform"`
	Status        PlatformAccountStatus `json:"status"`
	UpdatedAt     *time.Time            `json:"updated_at,omitempty"`
	Username      *string               `json:"username,omitempty"`
}

// DouyinAccountPlatform defines model for DouyinAccount.Platform.
type DouyinAccountPlatform string

// DraftFormat defines model for DraftFormat.
type DraftFormat string

// GeneratedBy defines model for GeneratedBy.
type GeneratedBy struct {
	AgentRunId   *string         `json:"agent_run_id,omitempty"`
	Id           string          `json:"id"`
	Instructions *string         `json:"instructions,omitempty"`
	Type         GeneratedByType `json:"type"`
	Version      *string         `json:"version,omitempty"`
}

// GeneratedByType defines model for GeneratedByType.
type GeneratedByType string

// MediaAssetLibraryScope defines model for MediaAssetLibraryScope.
type MediaAssetLibraryScope string

// PaginationCollabDocuments defines model for PaginationCollabDocuments.
type PaginationCollabDocuments struct {
	Items      []CollabDocument `json:"items"`
	Limit      int              `json:"limit"`
	Page       int              `json:"page"`
	Total      int              `json:"total"`
	TotalPages int              `json:"total_pages"`
}

// PaginationProjects defines model for PaginationProjects.
type PaginationProjects struct {
	// Cursor Opaque keyset cursor used for this page.
	Cursor  *string           `json:"cursor,omitempty"`
	HasMore bool              `json:"has_more"`
	Items   []ProjectListItem `json:"items"`
	Limit   int               `json:"limit"`

	// NextCursor Opaque keyset cursor for the next page.
	NextCursor *string `json:"next_cursor,omitempty"`
	Page       int     `json:"page"`
	Total      int     `json:"total"`
	TotalPages int     `json:"total_pages"`
}

// PlatformAccountStatus defines model for PlatformAccountStatus.
type PlatformAccountStatus string

// ProjectAccessSource defines model for ProjectAccessSource.
type ProjectAccessSource string

// ProjectActivitiesResponse defines model for ProjectActivitiesResponse.
type ProjectActivitiesResponse struct {
	Items []ProjectActivity `json:"items"`
}

// ProjectActivity defines model for ProjectActivity.
type ProjectActivity struct {
	ActorEmail     openapi_types.Email    `json:"actor_email"`
	ActorUserId    openapi_types.UUID     `json:"actor_user_id"`
	ActorUsername  string                 `json:"actor_username"`
	CreatedAt      time.Time              `json:"created_at"`
	EventType      ProjectActivityType    `json:"event_type"`
	Id             openapi_types.UUID     `json:"id"`
	Metadata       map[string]interface{} `json:"metadata"`
	ProjectId      openapi_types.UUID     `json:"project_id"`
	TargetEmail    *openapi_types.Email   `json:"target_email,omitempty"`
	TargetUserId   *openapi_types.UUID    `json:"target_user_id,omitempty"`
	TargetUsername *string                `json:"target_username,omitempty"`
}

// ProjectActivityType defines model for ProjectActivityType.
type ProjectActivityType string

// ProjectCollaborator defines model for ProjectCollaborator.
type ProjectCollaborator struct {
	CreatedAt time.Time               `json:"created_at"`
	CreatedBy openapi_types.UUID      `json:"created_by"`
	Email     openapi_types.Email     `json:"email"`
	ProjectId openapi_types.UUID      `json:"project_id"`
	Role      ProjectCollaboratorRole `json:"role"`
	UserId    openapi_types.UUID      `json:"user_id"`
	Username  string                  `json:"username"`
}

// ProjectCollaboratorRole defines model for ProjectCollaboratorRole.
type ProjectCollaboratorRole string

// ProjectCollaboratorsResponse defines model for ProjectCollaboratorsResponse.
type ProjectCollaboratorsResponse struct {
	Items []ProjectCollaborator `json:"items"`
}

// ProjectComment defines model for ProjectComment.
type ProjectComment struct {
	AnchorText     *string                `json:"anchor_text,omitempty"`
	AuthorEmail    openapi_types.Email    `json:"author_email"`
	AuthorId       openapi_types.UUID     `json:"author_id"`
	AuthorUsername string                 `json:"author_username"`
	Body           string                 `json:"body"`
	CreatedAt      time.Time              `json:"created_at"`
	Id             openapi_types.UUID     `json:"id"`
	Metadata       map[string]interface{} `json:"metadata"`
	ProjectId      openapi_types.UUID     `json:"project_id"`
	ResolvedAt     *time.Time             `json:"resolved_at,omitempty"`
	Status         ProjectCommentStatus   `json:"status"`
}

// ProjectCommentStatus defines model for ProjectCommentStatus.
type ProjectCommentStatus string

// ProjectCommentsResponse defines model for ProjectCommentsResponse.
type ProjectCommentsResponse struct {
	Items []ProjectComment `json:"items"`
}

// ProjectDetail defines model for ProjectDetail.
type ProjectDetail struct {
	AccessSource       *ProjectAccessSource       `json:"access_source,omitempty"`
	Activities         *[]ProjectActivity         `json:"activities,omitempty"`
	BrandProfileId     *openapi_types.UUID        `json:"brand_profile_id"`
	CollabDocumentId   *openapi_types.UUID        `json:"collab_document_id"`
	Collaborators      *[]ProjectCollaborator     `json:"collaborators,omitempty"`
	Comments           *[]ProjectComment          `json:"comments,omitempty"`
	CreatedAt          time.Time                  `json:"created_at"`
	Id                 openapi_types.UUID         `json:"id"`
	PermissionSources  *[]ProjectPermissionSource `json:"permission_sources,omitempty"`
	PublicationDetails *[]PublicationDetail       `json:"publication_details,omitempty"`
	Publications       []PublicationSummary       `json:"publications"`
	Role               ProjectRole                `json:"role"`
	ShareLinks         *[]ProjectShareLink        `json:"share_links,omitempty"`
	SourceContent      string                     `json:"source_content"`
	Status             ProjectStatus              `json:"status"`
	TemplateId         *openapi_types.UUID        `json:"template_id"`
	Title              string                     `json:"title"`
	UpdatedAt          time.Time                  `json:"updated_at"`
	UserId             openapi_types.UUID         `json:"user_id"`
	Versions           *[]ProjectVersion          `json:"versions,omitempty"`
	WorkspaceId        *openapi_types.UUID        `json:"workspace_id"`
}

// ProjectListItem defines model for ProjectListItem.
type ProjectListItem struct {
	AccessSource     *ProjectAccessSource `json:"access_source,omitempty"`
	BrandProfileId   *openapi_types.UUID  `json:"brand_profile_id"`
	CollabDocumentId *openapi_types.UUID  `json:"collab_document_id"`
	CreatedAt        time.Time            `json:"created_at"`
	Id               openapi_types.UUID   `json:"id"`
	Publications     []PublicationSummary `json:"publications"`
	Role             ProjectRole          `json:"role"`
	Status           ProjectStatus        `json:"status"`
	TemplateId       *openapi_types.UUID  `json:"template_id"`
	Title            string               `json:"title"`
	UpdatedAt        time.Time            `json:"updated_at"`
	UserId           openapi_types.UUID   `json:"user_id"`
	WorkspaceId      *openapi_types.UUID  `json:"workspace_id"`
}

// ProjectPermissionSource defines model for ProjectPermissionSource.
type ProjectPermissionSource struct {
	Role   string `json:"role"`
	Source string `json:"source"`
}

// ProjectPublications defines model for ProjectPublications.
type ProjectPublications struct {
	Items     []PublicationDetail `json:"items"`
	ProjectId openapi_types.UUID  `json:"project_id"`
}

// ProjectRole defines model for ProjectRole.
type ProjectRole string

// ProjectShareLink defines model for ProjectShareLink.
type ProjectShareLink struct {
	CreatedAt time.Time               `json:"created_at"`
	CreatedBy openapi_types.UUID      `json:"created_by"`
	ExpiresAt *time.Time              `json:"expires_at,omitempty"`
	Id        openapi_types.UUID      `json:"id"`
	ProjectId openapi_types.UUID      `json:"project_id"`
	RevokedAt *time.Time              `json:"revoked_at,omitempty"`
	Role      ProjectCollaboratorRole `json:"role"`
	Status    ProjectShareLinkStatus  `json:"status"`
}

// ProjectShareLinkStatus defines model for ProjectShareLinkStatus.
type ProjectShareLinkStatus string

// ProjectShareLinkWithToken defines model for ProjectShareLinkWithToken.
type ProjectShareLinkWithToken struct {
	CreatedAt time.Time               `json:"created_at"`
	CreatedBy openapi_types.UUID      `json:"created_by"`
	ExpiresAt *time.Time              `json:"expires_at,omitempty"`
	Id        openapi_types.UUID      `json:"id"`
	ProjectId openapi_types.UUID      `json:"project_id"`
	RevokedAt *time.Time              `json:"revoked_at,omitempty"`
	Role      ProjectCollaboratorRole `json:"role"`
	Status    ProjectShareLinkStatus  `json:"status"`
	Token     string                  `json:"token"`
	Url       string                  `json:"url"`
}

// ProjectShareLinksResponse defines model for ProjectShareLinksResponse.
type ProjectShareLinksResponse struct {
	Items []ProjectShareLink `json:"items"`
}

// ProjectStatus defines model for ProjectStatus.
type ProjectStatus string

// ProjectVersion defines model for ProjectVersion.
type ProjectVersion struct {
	CollabDocumentId *openapi_types.UUID `json:"collab_document_id,omitempty"`
	CollabSeq        int64               `json:"collab_seq"`
	CreatedAt        time.Time           `json:"created_at"`
	CreatedBy        openapi_types.UUID  `json:"created_by"`
	CreatorEmail     openapi_types.Email `json:"creator_email"`
	CreatorUsername  string              `json:"creator_username"`
	Id               openapi_types.UUID  `json:"id"`
	ProjectId        openapi_types.UUID  `json:"project_id"`
	Source           string              `json:"source"`
	Title            string              `json:"title"`
	VersionNumber    int                 `json:"version_number"`
}

// ProjectVersionsResponse defines model for ProjectVersionsResponse.
type ProjectVersionsResponse struct {
	Items []ProjectVersion `json:"items"`
}

// PublicationDetail defines model for PublicationDetail.
type PublicationDetail struct {
	AdaptedContent struct {
		Assets        *[]AdaptedAsset `json:"assets,omitempty"`
		Format        DraftFormat     `json:"format"`
		GeneratedBy   *GeneratedBy    `json:"generated_by,omitempty"`
		Html          *string         `json:"html,omitempty"`
		Markdown      *string         `json:"markdown,omitempty"`
		SchemaVersion *int            `json:"schema_version,omitempty"`

		// SourceRevision RFC3339 timestamp or a future revision identifier.
		SourceRevision *string `json:"source_revision,omitempty"`
		Summary        *string `json:"summary,omitempty"`
		Text           *string `json:"text,omitempty"`
	} `json:"adapted_content"`
	Config        map[string]interface{}    `json:"config"`
	CreatedAt     time.Time                 `json:"created_at"`
	DraftStatus   PublicationDraftStatus    `json:"draft_status"`
	Enabled       bool                      `json:"enabled"`
	ErrorMessage  *string                   `json:"error_message,omitempty"`
	Id            openapi_types.UUID        `json:"id"`
	LastAttemptAt *time.Time                `json:"last_attempt_at,omitempty"`
	Platform      PublicationDetailPlatform `json:"platform"`
	PublishUrl    *string                   `json:"publish_url,omitempty"`
	PublishedAt   *time.Time                `json:"published_at,omitempty"`
	RemoteId      *string                   `json:"remote_id,omitempty"`
	RetryCount    int                       `json:"retry_count"`
	ReviewStatus  PublicationReviewStatus   `json:"review_status"`
	Status        PublicationStatus         `json:"status"`
	SyncRequired  bool                      `json:"sync_required"`
	UpdatedAt     time.Time                 `json:"updated_at"`
}

// PublicationDetailPlatform defines model for PublicationDetail.Platform.
type PublicationDetailPlatform string

// PublicationDraftStatus defines model for PublicationDraftStatus.
type PublicationDraftStatus string

// PublicationReviewStatus defines model for PublicationReviewStatus.
type PublicationReviewStatus string

// PublicationStatus defines model for PublicationStatus.
type PublicationStatus string

// PublicationSummary defines model for PublicationSummary.
type PublicationSummary struct {
	DraftStatus  PublicationDraftStatus     `json:"draft_status"`
	Enabled      bool                       `json:"enabled"`
	Id           openapi_types.UUID         `json:"id"`
	Platform     PublicationSummaryPlatform `json:"platform"`
	PublishUrl   *string                    `json:"publish_url,omitempty"`
	ReviewStatus PublicationReviewStatus    `json:"review_status"`
	Status       PublicationStatus          `json:"status"`
	SyncRequired bool                       `json:"sync_required"`
}

// PublicationSummaryPlatform defines model for PublicationSummary.Platform.
type PublicationSummaryPlatform string

// PublishPlatform defines model for PublishPlatform.
type PublishPlatform string

// PublishResult defines model for PublishResult.
type PublishResult struct {
	BrowserSessionId *openapi_types.UUID    `json:"browser_session_id,omitempty"`
	ErrorMessage     *string                `json:"error_message,omitempty"`
	IdempotencyKey   *string                `json:"idempotency_key,omitempty"`
	JobId            *openapi_types.UUID    `json:"job_id,omitempty"`
	Platform         *PublishResultPlatform `json:"platform,omitempty"`
	PublishUrl       *string                `json:"publish_url,omitempty"`
	QueuedAt         *time.Time             `json:"queued_at,omitempty"`
	RemoteId         *string                `json:"remote_id,omitempty"`
	Status           PublishResultStatus    `json:"status"`
	StreamUrl        *string                `json:"stream_url,omitempty"`
}

// PublishResultPlatform defines model for PublishResult.Platform.
type PublishResultPlatform string

// PublishResultStatus defines model for PublishResultStatus.
type PublishResultStatus string

// RequirementStatus defines model for RequirementStatus.
type RequirementStatus struct {
	Message string                 `json:"message"`
	Status  RequirementStatusValue `json:"status"`
	Title   string                 `json:"title"`
}

// RequirementStatusValue defines model for RequirementStatusValue.
type RequirementStatusValue string

// RestoreProjectVersionResponse defines model for RestoreProjectVersionResponse.
type RestoreProjectVersionResponse struct {
	Project ProjectDetail  `json:"project"`
	Version ProjectVersion `json:"version"`
}

// SaveWechatAccountInput defines model for SaveWechatAccountInput.
type SaveWechatAccountInput struct {
	AppId     string  `json:"app_id"`
	AppSecret *string `json:"app_secret,omitempty"`
}

// SaveXAccountInput defines model for SaveXAccountInput.
type SaveXAccountInput struct {
	AccessToken       *string `json:"access_token,omitempty"`
	AccessTokenSecret *string `json:"access_token_secret,omitempty"`
	ApiKey            *string `json:"api_key,omitempty"`
	ApiSecret         *string `json:"api_secret,omitempty"`
	Username          *string `json:"username,omitempty"`
}

// StartBrowserSessionResult defines model for StartBrowserSessionResult.
type StartBrowserSessionResult struct {
	ExpiresAt            time.Time            `json:"expires_at"`
	SessionId            openapi_types.UUID   `json:"session_id"`
	Status               BrowserSessionStatus `json:"status"`
	StreamTokenExpiresAt time.Time            `json:"stream_token_expires_at"`
	StreamUrl            string               `json:"stream_url"`
}

// StartPublishBrowserSessionResult defines model for StartPublishBrowserSessionResult.
type StartPublishBrowserSessionResult struct {
	ExpiresAt            time.Time                                `json:"expires_at"`
	Platform             StartPublishBrowserSessionResultPlatform `json:"platform"`
	ProjectId            openapi_types.UUID                       `json:"project_id"`
	SessionId            openapi_types.UUID                       `json:"session_id"`
	Status               BrowserSessionStatus                     `json:"status"`
	StreamTokenExpiresAt time.Time                                `json:"stream_token_expires_at"`
	StreamUrl            string                                   `json:"stream_url"`
}

// StartPublishBrowserSessionResultPlatform defines model for StartPublishBrowserSessionResult.Platform.
type StartPublishBrowserSessionResultPlatform string

// UpdateCollabDocumentRequest defines model for UpdateCollabDocumentRequest.
type UpdateCollabDocumentRequest struct {
	Title string `json:"title"`
}

// UpdateProjectCollaboratorRequest defines model for UpdateProjectCollaboratorRequest.
type UpdateProjectCollaboratorRequest struct {
	Role ProjectCollaboratorRole `json:"role"`
}

// UpdateProjectCommentRequest defines model for UpdateProjectCommentRequest.
type UpdateProjectCommentRequest struct {
	Status UpdateProjectCommentRequestStatus `json:"status"`
}

// UpdateProjectCommentRequestStatus defines model for UpdateProjectCommentRequest.Status.
type UpdateProjectCommentRequestStatus string

// UpdateWorkspaceMemberRequest defines model for UpdateWorkspaceMemberRequest.
type UpdateWorkspaceMemberRequest struct {
	Role WorkspaceMemberRequestRole `json:"role"`
}

// UpdateWorkspaceRequest defines model for UpdateWorkspaceRequest.
type UpdateWorkspaceRequest struct {
	Name string  `json:"name"`
	Slug *string `json:"slug,omitempty"`
}

// WechatAccount defines model for WechatAccount.
type WechatAccount struct {
	AccountAuth   RequirementStatus     `json:"account_auth"`
	AppId         string                `json:"app_id"`
	HasAppSecret  bool                  `json:"has_app_secret"`
	IpWhitelist   RequirementStatus     `json:"ip_whitelist"`
	LastTestError *string               `json:"last_test_error,omitempty"`
	LastTestedAt  *time.Time            `json:"last_tested_at,omitempty"`
	Platform      WechatAccountPlatform `json:"platform"`
	Status        PlatformAccountStatus `json:"status"`
	UpdatedAt     *time.Time            `json:"updated_at,omitempty"`
}

// WechatAccountPlatform defines model for WechatAccount.Platform.
type WechatAccountPlatform string

// WechatConnectionTestResult defines model for WechatConnectionTestResult.
type WechatConnectionTestResult struct {
	AccountAuth RequirementStatus    `json:"account_auth"`
	Connected   bool                 `json:"connected"`
	ErrCode     *int                 `json:"err_code,omitempty"`
	ErrMsg      *string              `json:"err_msg,omitempty"`
	IpWhitelist RequirementStatus    `json:"ip_whitelist"`
	Message     string               `json:"message"`
	Status      ConnectionTestStatus `json:"status"`
	TestedAt    time.Time            `json:"tested_at"`
}

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt   time.Time          `json:"created_at"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	OwnerUserId openapi_types.UUID `json:"owner_user_id"`
	Role        WorkspaceRole      `json:"role"`
	Slug        *string            `json:"slug,omitempty"`
	Status      WorkspaceStatus    `json:"status"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// WorkspaceActivitiesResponse defines model for WorkspaceActivitiesResponse.
type WorkspaceActivitiesResponse struct {
	Items []WorkspaceActivity `json:"items"`
}

// WorkspaceActivity defines model for WorkspaceActivity.
type WorkspaceActivity struct {
	ActorEmail     openapi_types.Email    `json:"actor_email"`
	ActorUserId    openapi_types.UUID     `json:"actor_user_id"`
	ActorUsername  string                 `json:"actor_username"`
	CreatedAt      time.Time              `json:"created_at"`
	EventType      WorkspaceActivityType  `json:"event_type"`
	Id             openapi_types.UUID     `json:"id"`
	Metadata       map[string]interface{} `json:"metadata"`
	TargetEmail    *openapi_types.Email   `json:"target_email,omitempty"`
	TargetUserId   *openapi_types.UUID    `json:"target_user_id,omitempty"`
	TargetUsername *string                `json:"target_username,omitempty"`
	WorkspaceId    openapi_types.UUID     `json:"workspace_id"`
}

// WorkspaceActivityType defines model for WorkspaceActivityType.
type WorkspaceActivityType string

// WorkspaceInvite defines model for WorkspaceInvite.
type WorkspaceInvite struct {
	AcceptedAt  *time.Time            `json:"accepted_at,omitempty"`
	AcceptedBy  *openapi_types.UUID   `json:"accepted_by,omitempty"`
	CreatedAt   time.Time             `json:"created_at"`
	Email       openapi_types.Email   `json:"email"`
	ExpiresAt   time.Time             `json:"expires_at"`
	Id          openapi_types.UUID    `json:"id"`
	InvitedBy   openapi_types.UUID    `json:"invited_by"`
	RevokedAt   *time.Time            `json:"revoked_at,omitempty"`
	Role        WorkspaceRole         `json:"role"`
	Status      WorkspaceInviteStatus `json:"status"`
	UpdatedAt   time.Time             `json:"updated_at"`
	WorkspaceId openapi_types.UUID    `json:"workspace_id"`
}

// WorkspaceInviteStatus defines model for WorkspaceInvite.Status.
type WorkspaceInviteStatus string

// WorkspaceInviteWithToken defines model for WorkspaceInviteWithToken.
type WorkspaceInviteWithToken struct {
	AcceptedAt  *time.Time                     `json:"accepted_at,omitempty"`
	AcceptedBy  *openapi_types.UUID            `json:"accepted_by,omitempty"`
	CreatedAt   time.Time                      `json:"created_at"`
	Email       openapi_types.Email            `json:"email"`
	ExpiresAt   time.Time                      `json:"expires_at"`
	Id          openapi_types.UUID             `json:"id"`
	InvitedBy   openapi_types.UUID             `json:"invited_by"`
	RevokedAt   *time.Time                     `json:"revoked_at,omitempty"`
	Role        WorkspaceRole                  `json:"role"`
	Status      WorkspaceInviteWithTokenStatus `json:"status"`
	Token       string                         `json:"token"`
	UpdatedAt   time.Time                      `json:"updated_at"`
	WorkspaceId openapi_types.UUID             `json:"workspace_id"`
}

// WorkspaceInviteWithTokenStatus defines model for WorkspaceInviteWithToken.Status.
type WorkspaceInviteWithTokenStatus string

// WorkspaceInvitesResponse defines model for WorkspaceInvitesResponse.
type WorkspaceInvitesResponse struct {
	Items []WorkspaceInvite `json:"items"`
}

// WorkspaceMember defines model for WorkspaceMember.
type WorkspaceMember struct {
	CreatedAt   time.Time           `json:"created_at"`
	Email       openapi_types.Email `json:"email"`
	InvitedBy   *openapi_types.UUID `json:"invited_by,omitempty"`
	JoinedAt    *time.Time          `json:"joined_at,omitempty"`
	Role        WorkspaceRole       `json:"role"`
	UserId      openapi_types.UUID  `json:"user_id"`
	Username    string              `json:"username"`
	WorkspaceId openapi_types.UUID  `json:"workspace_id"`
}

// WorkspaceMemberRequestRole defines model for WorkspaceMemberRequestRole.
type WorkspaceMemberRequestRole string

// WorkspaceMembersResponse defines model for WorkspaceMembersResponse.
type WorkspaceMembersResponse struct {
	Items []WorkspaceMember `json:"items"`
}

// WorkspaceRole defines model for WorkspaceRole.
type WorkspaceRole string

// WorkspaceStatus defines model for WorkspaceStatus.
type WorkspaceStatus string

// WorkspacesResponse defines model for WorkspacesResponse.
type WorkspacesResponse struct {
	Items []Workspace `json:"items"`
}

// XAccount defines model for XAccount.
type XAccount struct {
	AccountAuth          RequirementStatus     `json:"account_auth"`
	ApiKey               *string               `json:"api_key,omitempty"`
	AuthType             XAccountAuthType      `json:"auth_type"`
	ExpiresAt            *time.Time            `json:"expires_at,omitempty"`
	HasAccessToken       bool                  `json:"has_access_token"`
	HasAccessTokenSecret bool                  `json:"has_access_token_secret"`
	HasApiSecret         bool                  `json:"has_api_secret"`
	HasOauth2Refresh     bool                  `json:"has_oauth2_refresh"`
	LastTestError        *string               `json:"last_test_error,omitempty"`
	LastTestedAt         *time.Time            `json:"last_tested_at,omitempty"`
	Platform             XAccountPlatform      `json:"platform"`
	PublishAccess        RequirementStatus     `json:"publish_access"`
	Status               PlatformAccountStatus `json:"status"`
	UpdatedAt            *time.Time            `json:"updated_at,omitempty"`
	Username             *string               `json:"username,omitempty"`
}

// XAccountAuthType defines model for XAccount.AuthType.
type XAccountAuthType string

// XAccountPlatform defines model for XAccount.Platform.
type XAccountPlatform string

// XConnectionTestResult defines model for XConnectionTestResult.
type XConnectionTestResult struct {
	AccountAuth   RequirementStatus    `json:"account_auth"`
	Connected     bool                 `json:"connected"`
	Message       string               `json:"message"`
	Name          *string              `json:"name,omitempty"`
	PublishAccess RequirementStatus    `json:"publish_access"`
	Status        ConnectionTestStatus `json:"status"`
	TestedAt      time.Time            `json:"tested_at"`
	UserId        *string              `json:"user_id,omitempty"`
	Username      *string              `json:"username,omitempty"`
}

// ZhihuAccount defines model for ZhihuAccount.
type ZhihuAccount struct {
	AvatarUrl     *string               `json:"avatar_url,omitempty"`
	LastTestError *string               `json:"last_test_error,omitempty"`
	LastTestedAt  *time.Time            `json:"last_tested_at,omitempty"`
	Platform      ZhihuAccountPlatform  `json:"platform"`
	Status        PlatformAccountStatus `json:"status"`
	UpdatedAt     *time.Time            `json:"updated_at,omitempty"`
	Username      *string               `json:"username,omitempty"`
}

// ZhihuAccountPlatform defines model for ZhihuAccount.Platform.
type ZhihuAccountPlatform string
