// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: mpp/contentpipeline/v1/content_pipeline.proto

package contentpipelinepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaAssetProcessor_ProcessAsset_FullMethodName = "/mpp.contentpipeline.v1.MediaAssetProcessor/ProcessAsset"
)

// MediaAssetProcessorClient is the client API for MediaAssetProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaAssetProcessorClient interface {
	ProcessAsset(ctx context.Context, in *ProcessAssetRequest, opts ...grpc.CallOption) (*ProcessAssetResponse, error)
}

type mediaAssetProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaAssetProcessorClient(cc grpc.ClientConnInterface) MediaAssetProcessorClient {
	return &mediaAssetProcessorClient{cc}
}

func (c *mediaAssetProcessorClient) ProcessAsset(ctx context.Context, in *ProcessAssetRequest, opts ...grpc.CallOption) (*ProcessAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessAssetResponse)
	err := c.cc.Invoke(ctx, MediaAssetProcessor_ProcessAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaAssetProcessorServer is the server API for MediaAssetProcessor service.
// All implementations must embed UnimplementedMediaAssetProcessorServer
// for forward compatibility.
type MediaAssetProcessorServer interface {
	ProcessAsset(context.Context, *ProcessAssetRequest) (*ProcessAssetResponse, error)
	mustEmbedUnimplementedMediaAssetProcessorServer()
}

// UnimplementedMediaAssetProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaAssetProcessorServer struct{}

func (UnimplementedMediaAssetProcessorServer) ProcessAsset(context.Context, *ProcessAssetRequest) (*ProcessAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessAsset not implemented")
}
func (UnimplementedMediaAssetProcessorServer) mustEmbedUnimplementedMediaAssetProcessorServer() {}
func (UnimplementedMediaAssetProcessorServer) testEmbeddedByValue()                             {}

// UnsafeMediaAssetProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaAssetProcessorServer will
// result in compilation errors.
type UnsafeMediaAssetProcessorServer interface {
	mustEmbedUnimplementedMediaAssetProcessorServer()
}

func RegisterMediaAssetProcessorServer(s grpc.ServiceRegistrar, srv MediaAssetProcessorServer) {
	// If the following call pancis, it indicates UnimplementedMediaAssetProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaAssetProcessor_ServiceDesc, srv)
}

func _MediaAssetProcessor_ProcessAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaAssetProcessorServer).ProcessAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaAssetProcessor_ProcessAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaAssetProcessorServer).ProcessAsset(ctx, req.(*ProcessAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaAssetProcessor_ServiceDesc is the grpc.ServiceDesc for MediaAssetProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaAssetProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpp.contentpipeline.v1.MediaAssetProcessor",
	HandlerType: (*MediaAssetProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessAsset",
			Handler:    _MediaAssetProcessor_ProcessAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpp/contentpipeline/v1/content_pipeline.proto",
}

const (
	PlatformDraftCompiler_CompileDrafts_FullMethodName = "/mpp.contentpipeline.v1.PlatformDraftCompiler/CompileDrafts"
)

// PlatformDraftCompilerClient is the client API for PlatformDraftCompiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatformDraftCompilerClient interface {
	CompileDrafts(ctx context.Context, in *CompileDraftsRequest, opts ...grpc.CallOption) (*CompileDraftsResponse, error)
}

type platformDraftCompilerClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformDraftCompilerClient(cc grpc.ClientConnInterface) PlatformDraftCompilerClient {
	return &platformDraftCompilerClient{cc}
}

func (c *platformDraftCompilerClient) CompileDrafts(ctx context.Context, in *CompileDraftsRequest, opts ...grpc.CallOption) (*CompileDraftsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileDraftsResponse)
	err := c.cc.Invoke(ctx, PlatformDraftCompiler_CompileDrafts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformDraftCompilerServer is the server API for PlatformDraftCompiler service.
// All implementations must embed UnimplementedPlatformDraftCompilerServer
// for forward compatibility.
type PlatformDraftCompilerServer interface {
	CompileDrafts(context.Context, *CompileDraftsRequest) (*CompileDraftsResponse, error)
	mustEmbedUnimplementedPlatformDraftCompilerServer()
}

// UnimplementedPlatformDraftCompilerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformDraftCompilerServer struct{}

func (UnimplementedPlatformDraftCompilerServer) CompileDrafts(context.Context, *CompileDraftsRequest) (*CompileDraftsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompileDrafts not implemented")
}
func (UnimplementedPlatformDraftCompilerServer) mustEmbedUnimplementedPlatformDraftCompilerServer() {}
func (UnimplementedPlatformDraftCompilerServer) testEmbeddedByValue()                               {}

// UnsafePlatformDraftCompilerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformDraftCompilerServer will
// result in compilation errors.
type UnsafePlatformDraftCompilerServer interface {
	mustEmbedUnimplementedPlatformDraftCompilerServer()
}

func RegisterPlatformDraftCompilerServer(s grpc.ServiceRegistrar, srv PlatformDraftCompilerServer) {
	// If the following call pancis, it indicates UnimplementedPlatformDraftCompilerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformDraftCompiler_ServiceDesc, srv)
}

func _PlatformDraftCompiler_CompileDrafts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileDraftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformDraftCompilerServer).CompileDrafts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformDraftCompiler_CompileDrafts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformDraftCompilerServer).CompileDrafts(ctx, req.(*CompileDraftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformDraftCompiler_ServiceDesc is the grpc.ServiceDesc for PlatformDraftCompiler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformDraftCompiler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpp.contentpipeline.v1.PlatformDraftCompiler",
	HandlerType: (*PlatformDraftCompilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompileDrafts",
			Handler:    _PlatformDraftCompiler_CompileDrafts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpp/contentpipeline/v1/content_pipeline.proto",
}
