// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: mpp/contentpipeline/v1/content_pipeline.proto

package contentpipelinepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Usage         string                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Source        *MediaSource           `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Constraints   *MediaConstraints      `protobuf:"bytes,5,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessAssetRequest) Reset() {
	*x = ProcessAssetRequest{}
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAssetRequest) ProtoMessage() {}

func (x *ProcessAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAssetRequest.ProtoReflect.Descriptor instead.
func (*ProcessAssetRequest) Descriptor() ([]byte, []int) {
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessAssetRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProcessAssetRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ProcessAssetRequest) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *ProcessAssetRequest) GetSource() *MediaSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ProcessAssetRequest) GetConstraints() *MediaConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type MediaSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MediaSource_Url
	//	*MediaSource_DataUrl
	//	*MediaSource_ObjectRef
	Value         isMediaSource_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaSource) Reset() {
	*x = MediaSource{}
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSource) ProtoMessage() {}

func (x *MediaSource) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSource.ProtoReflect.Descriptor instead.
func (*MediaSource) Descriptor() ([]byte, []int) {
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *MediaSource) GetValue() isMediaSource_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MediaSource) GetUrl() string {
	if x != nil {
		if x, ok := x.Value.(*MediaSource_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *MediaSource) GetDataUrl() string {
	if x != nil {
		if x, ok := x.Value.(*MediaSource_DataUrl); ok {
			return x.DataUrl
		}
	}
	return ""
}

func (x *MediaSource) GetObjectRef() string {
	if x != nil {
		if x, ok := x.Value.(*MediaSource_ObjectRef); ok {
			return x.ObjectRef
		}
	}
	return ""
}

type isMediaSource_Value interface {
	isMediaSource_Value()
}

type MediaSource_Url struct {
	Url string `protobuf:"bytes,1,opt,name=url,proto3,oneof"`
}

type MediaSource_DataUrl struct {
	DataUrl string `protobuf:"bytes,2,opt,name=data_url,json=dataUrl,proto3,oneof"`
}

type MediaSource_ObjectRef struct {
	ObjectRef string `protobuf:"bytes,3,opt,name=object_ref,json=objectRef,proto3,oneof"`
}

func (*MediaSource_Url) isMediaSource_Value() {}

func (*MediaSource_DataUrl) isMediaSource_Value() {}

func (*MediaSource_ObjectRef) isMediaSource_Value() {}

type MediaConstraints struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxBytes           uint64                 `protobuf:"varint,1,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	PreferredMimeTypes []string               `protobuf:"bytes,2,rep,name=preferred_mime_types,json=preferredMimeTypes,proto3" json:"preferred_mime_types,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MediaConstraints) Reset() {
	*x = MediaConstraints{}
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaConstraints) ProtoMessage() {}

func (x *MediaConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaConstraints.ProtoReflect.Descriptor instead.
func (*MediaConstraints) Descriptor() ([]byte, []int) {
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *MediaConstraints) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *MediaConstraints) GetPreferredMimeTypes() []string {
	if x != nil {
		return x.PreferredMimeTypes
	}
	return nil
}

type ProcessAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *ProcessedAsset        `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessAssetResponse) Reset() {
	*x = ProcessAssetResponse{}
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAssetResponse) ProtoMessage() {}

func (x *ProcessAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAssetResponse.ProtoReflect.Descriptor instead.
func (*ProcessAssetResponse) Descriptor() ([]byte, []int) {
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessAssetResponse) GetAsset() *ProcessedAsset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *ProcessAssetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessAssetResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ProcessedAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectRef     string                 `protobuf:"bytes,2,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	ByteSize      uint64                 `protobuf:"varint,4,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	Width         uint32                 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Sha256        string                 `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedAsset) Reset() {
	*x = ProcessedAsset{}
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedAsset) ProtoMessage() {}

func (x *ProcessedAsset) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedAsset.ProtoReflect.Descriptor instead.
func (*ProcessedAsset) Descriptor() ([]byte, []int) {
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessedAsset) GetObjectRef() string {
	if x != nil {
		return x.ObjectRef
	}
	return ""
}

func (x *ProcessedAsset) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ProcessedAsset) GetByteSize() uint64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *ProcessedAsset) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ProcessedAsset) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProcessedAsset) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type CompileDraftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Project       *SourceProject         `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Targets       []*DraftTarget         `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileDraftsRequest) Reset() {
	*x = CompileDraftsRequest{}
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileDraftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileDraftsRequest) ProtoMessage() {}

func (x *CompileDraftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileDraftsRequest.ProtoReflect.Descriptor instead.
func (*CompileDraftsRequest) Descriptor() ([]byte, []int) {
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP(), []int{5}
}

func (x *CompileDraftsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompileDraftsRequest) GetProject() *SourceProject {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *CompileDraftsRequest) GetTargets() []*DraftTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type SourceProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SourceFormat  string                 `protobuf:"bytes,3,opt,name=source_format,json=sourceFormat,proto3" json:"source_format,omitempty"`
	SourceContent string                 `protobuf:"bytes,4,opt,name=source_content,json=sourceContent,proto3" json:"source_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceProject) Reset() {
	*x = SourceProject{}
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceProject) ProtoMessage() {}

func (x *SourceProject) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceProject.ProtoReflect.Descriptor instead.
func (*SourceProject) Descriptor() ([]byte, []int) {
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP(), []int{6}
}

func (x *SourceProject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SourceProject) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SourceProject) GetSourceFormat() string {
	if x != nil {
		return x.SourceFormat
	}
	return ""
}

func (x *SourceProject) GetSourceContent() string {
	if x != nil {
		return x.SourceContent
	}
	return ""
}

type DraftTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftTarget) Reset() {
	*x = DraftTarget{}
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftTarget) ProtoMessage() {}

func (x *DraftTarget) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftTarget.ProtoReflect.Descriptor instead.
func (*DraftTarget) Descriptor() ([]byte, []int) {
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP(), []int{7}
}

func (x *DraftTarget) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DraftTarget) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *DraftTarget) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type CompileDraftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drafts        []*CompiledDraft       `protobuf:"bytes,1,rep,name=drafts,proto3" json:"drafts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileDraftsResponse) Reset() {
	*x = CompileDraftsResponse{}
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileDraftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileDraftsResponse) ProtoMessage() {}

func (x *CompileDraftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileDraftsResponse.ProtoReflect.Descriptor instead.
func (*CompileDraftsResponse) Descriptor() ([]byte, []int) {
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP(), []int{8}
}

func (x *CompileDraftsResponse) GetDrafts() []*CompiledDraft {
	if x != nil {
		return x.Drafts
	}
	return nil
}

type CompiledDraft struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Platform           string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Profile            string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AdaptedContentJson string                 `protobuf:"bytes,4,opt,name=adapted_content_json,json=adaptedContentJson,proto3" json:"adapted_content_json,omitempty"`
	Summary            string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Warnings           []string               `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompiledDraft) Reset() {
	*x = CompiledDraft{}
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledDraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledDraft) ProtoMessage() {}

func (x *CompiledDraft) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledDraft.ProtoReflect.Descriptor instead.
func (*CompiledDraft) Descriptor() ([]byte, []int) {
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP(), []int{9}
}

func (x *CompiledDraft) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CompiledDraft) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *CompiledDraft) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CompiledDraft) GetAdaptedContentJson() string {
	if x != nil {
		return x.AdaptedContentJson
	}
	return ""
}

func (x *CompiledDraft) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CompiledDraft) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

var File_mpp_contentpipeline_v1_content_pipeline_proto protoreflect.FileDescriptor

const file_mpp_contentpipeline_v1_content_pipeline_proto_rawDesc = "" +
	"\n" +
	"-mpp/contentpipeline/v1/content_pipeline.proto\x12\x16mpp.contentpipeline.v1\"\xef\x01\n" +
	"\x13ProcessAssetRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\tR\x05usage\x12;\n" +
	"\x06source\x18\x04 \x01(\v2#.mpp.contentpipeline.v1.MediaSourceR\x06source\x12J\n" +
	"\vconstraints\x18\x05 \x01(\v2(.mpp.contentpipeline.v1.MediaConstraintsR\vconstraints\"h\n" +
	"\vMediaSource\x12\x12\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x12\x1b\n" +
	"\bdata_url\x18\x02 \x01(\tH\x00R\adataUrl\x12\x1f\n" +
	"\n" +
	"object_ref\x18\x03 \x01(\tH\x00R\tobjectRefB\a\n" +
	"\x05value\"a\n" +
	"\x10MediaConstraints\x12\x1b\n" +
	"\tmax_bytes\x18\x01 \x01(\x04R\bmaxBytes\x120\n" +
	"\x14preferred_mime_types\x18\x02 \x03(\tR\x12preferredMimeTypes\"\x88\x01\n" +
	"\x14ProcessAssetResponse\x12<\n" +
	"\x05asset\x18\x01 \x01(\v2&.mpp.contentpipeline.v1.ProcessedAssetR\x05asset\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"\xb5\x01\n" +
	"\x0eProcessedAsset\x12\x1d\n" +
	"\n" +
	"object_ref\x18\x02 \x01(\tR\tobjectRef\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tbyte_size\x18\x04 \x01(\x04R\bbyteSize\x12\x14\n" +
	"\x05width\x18\x05 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\rR\x06height\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256J\x04\b\x01\x10\x02\"\xb5\x01\n" +
	"\x14CompileDraftsRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12?\n" +
	"\aproject\x18\x02 \x01(\v2%.mpp.contentpipeline.v1.SourceProjectR\aproject\x12=\n" +
	"\atargets\x18\x03 \x03(\v2#.mpp.contentpipeline.v1.DraftTargetR\atargets\"\x81\x01\n" +
	"\rSourceProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rsource_format\x18\x03 \x01(\tR\fsourceFormat\x12%\n" +
	"\x0esource_content\x18\x04 \x01(\tR\rsourceContent\"d\n" +
	"\vDraftTarget\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\"V\n" +
	"\x15CompileDraftsResponse\x12=\n" +
	"\x06drafts\x18\x01 \x03(\v2%.mpp.contentpipeline.v1.CompiledDraftR\x06drafts\"\xc5\x01\n" +
	"\rCompiledDraft\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x120\n" +
	"\x14adapted_content_json\x18\x04 \x01(\tR\x12adaptedContentJson\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x1a\n" +
	"\bwarnings\x18\x06 \x03(\tR\bwarnings2\x80\x01\n" +
	"\x13MediaAssetProcessor\x12i\n" +
	"\fProcessAsset\x12+.mpp.contentpipeline.v1.ProcessAssetRequest\x1a,.mpp.contentpipeline.v1.ProcessAssetResponse2\x85\x01\n" +
	"\x15PlatformDraftCompiler\x12l\n" +
	"\rCompileDrafts\x12,.mpp.contentpipeline.v1.CompileDraftsRequest\x1a-.mpp.contentpipeline.v1.CompileDraftsResponseBZZXgithub.com/kurodakayn/mpp-backend/internal/contracts/contentpipelinepb;contentpipelinepbb\x06proto3"

var (
	file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescOnce sync.Once
	file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescData []byte
)

func file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescGZIP() []byte {
	file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescOnce.Do(func() {
		file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpp_contentpipeline_v1_content_pipeline_proto_rawDesc), len(file_mpp_contentpipeline_v1_content_pipeline_proto_rawDesc)))
	})
	return file_mpp_contentpipeline_v1_content_pipeline_proto_rawDescData
}

var file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mpp_contentpipeline_v1_content_pipeline_proto_goTypes = []any{
	(*ProcessAssetRequest)(nil),   // 0: mpp.contentpipeline.v1.ProcessAssetRequest
	(*MediaSource)(nil),           // 1: mpp.contentpipeline.v1.MediaSource
	(*MediaConstraints)(nil),      // 2: mpp.contentpipeline.v1.MediaConstraints
	(*ProcessAssetResponse)(nil),  // 3: mpp.contentpipeline.v1.ProcessAssetResponse
	(*ProcessedAsset)(nil),        // 4: mpp.contentpipeline.v1.ProcessedAsset
	(*CompileDraftsRequest)(nil),  // 5: mpp.contentpipeline.v1.CompileDraftsRequest
	(*SourceProject)(nil),         // 6: mpp.contentpipeline.v1.SourceProject
	(*DraftTarget)(nil),           // 7: mpp.contentpipeline.v1.DraftTarget
	(*CompileDraftsResponse)(nil), // 8: mpp.contentpipeline.v1.CompileDraftsResponse
	(*CompiledDraft)(nil),         // 9: mpp.contentpipeline.v1.CompiledDraft
}
var file_mpp_contentpipeline_v1_content_pipeline_proto_depIdxs = []int32{
	1, // 0: mpp.contentpipeline.v1.ProcessAssetRequest.source:type_name -> mpp.contentpipeline.v1.MediaSource
	2, // 1: mpp.contentpipeline.v1.ProcessAssetRequest.constraints:type_name -> mpp.contentpipeline.v1.MediaConstraints
	4, // 2: mpp.contentpipeline.v1.ProcessAssetResponse.asset:type_name -> mpp.contentpipeline.v1.ProcessedAsset
	6, // 3: mpp.contentpipeline.v1.CompileDraftsRequest.project:type_name -> mpp.contentpipeline.v1.SourceProject
	7, // 4: mpp.contentpipeline.v1.CompileDraftsRequest.targets:type_name -> mpp.contentpipeline.v1.DraftTarget
	9, // 5: mpp.contentpipeline.v1.CompileDraftsResponse.drafts:type_name -> mpp.contentpipeline.v1.CompiledDraft
	0, // 6: mpp.contentpipeline.v1.MediaAssetProcessor.ProcessAsset:input_type -> mpp.contentpipeline.v1.ProcessAssetRequest
	5, // 7: mpp.contentpipeline.v1.PlatformDraftCompiler.CompileDrafts:input_type -> mpp.contentpipeline.v1.CompileDraftsRequest
	3, // 8: mpp.contentpipeline.v1.MediaAssetProcessor.ProcessAsset:output_type -> mpp.contentpipeline.v1.ProcessAssetResponse
	8, // 9: mpp.contentpipeline.v1.PlatformDraftCompiler.CompileDrafts:output_type -> mpp.contentpipeline.v1.CompileDraftsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_mpp_contentpipeline_v1_content_pipeline_proto_init() }
func file_mpp_contentpipeline_v1_content_pipeline_proto_init() {
	if File_mpp_contentpipeline_v1_content_pipeline_proto != nil {
		return
	}
	file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes[1].OneofWrappers = []any{
		(*MediaSource_Url)(nil),
		(*MediaSource_DataUrl)(nil),
		(*MediaSource_ObjectRef)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpp_contentpipeline_v1_content_pipeline_proto_rawDesc), len(file_mpp_contentpipeline_v1_content_pipeline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mpp_contentpipeline_v1_content_pipeline_proto_goTypes,
		DependencyIndexes: file_mpp_contentpipeline_v1_content_pipeline_proto_depIdxs,
		MessageInfos:      file_mpp_contentpipeline_v1_content_pipeline_proto_msgTypes,
	}.Build()
	File_mpp_contentpipeline_v1_content_pipeline_proto = out.File
	file_mpp_contentpipeline_v1_content_pipeline_proto_goTypes = nil
	file_mpp_contentpipeline_v1_content_pipeline_proto_depIdxs = nil
}
