// Code generated by contracts/generate-platform-capabilities.ts; DO NOT EDIT.

export const PLATFORM_CAPABILITY_SCHEMA_VERSION = 1 as const;

export const PLATFORM_CAPABILITIES = [
  {
    platform: "zhihu",
    supported_modes: ["extension", "remote"],
    preferred_mode: "extension",
    adapter_key: "ARTICLE_ZHIHU",
    inject_url: "https://zhuanlan.zhihu.com/write",
    content_kinds: ["article"],
    target_formats: ["markdown", "html"],
    requires_review: true,
    auto_publish_allowed: false,
  },
  {
    platform: "x",
    supported_modes: ["extension"],
    preferred_mode: "extension",
    adapter_key: "POST_X",
    inject_url: "https://x.com/compose/post",
    content_kinds: ["dynamic_post"],
    target_formats: ["text"],
    requires_review: true,
    auto_publish_allowed: false,
  },
  {
    platform: "douyin",
    supported_modes: ["extension"],
    preferred_mode: "extension",
    adapter_key: "DYNAMIC_DOUYIN",
    inject_url:
      "https://creator.douyin.com/creator-micro/content/upload?default-tab=5",
    inject_urls: [
      "https://creator.douyin.com/creator-micro/content/upload",
      "https://creator.douyin.com/creator-micro/content/post/article",
    ],
    content_kinds: ["article", "image_video"],
    target_formats: ["text"],
    requires_review: true,
    auto_publish_allowed: false,
  },
  {
    platform: "xiaohongshu",
    supported_modes: ["extension"],
    preferred_mode: "extension",
    adapter_key: "NOTE_XIAOHONGSHU",
    inject_url: "https://creator.xiaohongshu.com/publish/publish",
    content_kinds: ["image_note"],
    target_formats: ["text"],
    requires_review: true,
    auto_publish_allowed: false,
  },
  {
    platform: "bilibili",
    supported_modes: ["extension"],
    preferred_mode: "extension",
    adapter_key: "DYNAMIC_BILIBILI",
    inject_url: "https://t.bilibili.com",
    content_kinds: ["dynamic_post"],
    target_formats: ["text"],
    requires_review: true,
    auto_publish_allowed: false,
  },
] as const;

export const ADAPTER_SCRIPT_FILES = {
  ARTICLE_ZHIHU: "/content-scripts/zhihu-article.js",
  POST_X: "/content-scripts/x-post.js",
  DYNAMIC_DOUYIN: "/content-scripts/douyin-dynamic.js",
  NOTE_XIAOHONGSHU: "/content-scripts/xiaohongshu-note.js",
  DYNAMIC_BILIBILI: "/content-scripts/bilibili-dynamic.js",
} as const;
