// Code generated by contracts/generate-platform-capabilities.ts; DO NOT EDIT.

export const PLATFORM_CAPABILITY_SCHEMA_VERSION = 1 as const;

export const PLATFORM_TABS = [
  {
    value: "wechat",
    label: "platforms.wechat",
    defaultLabel: "WeChat",
    icon: "/icons/platforms/wechat.svg",
    autoPublishAllowed: true,
    preferredPublishMode: "api",
    draftFormat: "html"
  },
  {
    value: "zhihu",
    label: "platforms.zhihu",
    defaultLabel: "Zhihu",
    icon: "/icons/platforms/zhihu.svg",
    autoPublishAllowed: true,
    preferredPublishMode: "headless_browser",
    draftFormat: "markdown"
  },
  {
    value: "x",
    label: "platforms.x",
    defaultLabel: "X",
    icon: "/icons/platforms/x.svg",
    autoPublishAllowed: true,
    preferredPublishMode: "api",
    draftFormat: "text"
  },
  {
    value: "douyin",
    label: "platforms.douyin",
    defaultLabel: "Douyin",
    icon: "/icons/platforms/douyin.svg",
    autoPublishAllowed: false,
    preferredPublishMode: "extension",
    draftFormat: "text"
  }
] as const;
