// Code generated by contracts/generate-platform-capabilities.ts; DO NOT EDIT.

use super::{DraftFormat, DraftProfile};

pub(super) const SUPPORTED_DRAFT_PROFILES: &[DraftProfile] = &[
    DraftProfile {
        platform: "wechat",
        profile: "wechat@v1",
        schema_version: 1,
        format: DraftFormat::Html,
    },
    DraftProfile {
        platform: "zhihu",
        profile: "zhihu@v1",
        schema_version: 1,
        format: DraftFormat::Markdown,
    },
    DraftProfile {
        platform: "x",
        profile: "x@v1",
        schema_version: 1,
        format: DraftFormat::Text,
    },
    DraftProfile {
        platform: "douyin",
        profile: "douyin@v1",
        schema_version: 1,
        format: DraftFormat::Text,
    },
];
